// SyncEngine — top-level coordinator for P2P sync (design.md §3, ticket T-008).
//
// Owns the LoroDoc, the SyncStore, the Transport, and the Bridge. On
// `start(state)` it:
//   1. loads (or generates + persists) the iroh node secret and the
//      shared sync_doc_secret from the `app_state` KV table
//   2. opens the on-disk SyncStore (snapshot + WAL) and hydrates a
//      LoroDoc from it
//   3. brings up the Transport (iroh endpoint + gossip topic)
//   4. wires up three background tasks behind the same CancellationToken:
//        a. local-update pump — every Loro commit fires the doc's
//           `subscribe_local_update` callback; the bytes are appended to
//           the WAL and broadcast on gossip as `WireMsg::Update`
//        b. inbox handler   — drains `Transport::subscribe()`, importing
//           inbound `Update` / `Snapshot` / `StateResponse` payloads and
//           replying to `StateRequest` with the missing-since-vv bytes
//        c. checkpoint scheduler — fires every `CHECKPOINT_INTERVAL` and
//           also on the local-update pump's notification when WAL entries
//           cross `CHECKPOINT_WAL_THRESHOLD`
//
// The local-update callback is the natural echo-storm guard for the
// broadcast path: Loro fires it only for updates generated by THIS
// doc's commits (not for `import()`), so remote messages can't bounce
// back out as broadcasts. The bridge's apply_remote → SQLite path
// (T-010) needs its own guard via the `Origin` marker.

#![allow(dead_code)]

use crate::error::{AppError, Result};
use crate::p2p::bridge::Bridge;
use crate::p2p::doc::SyncDoc;
use crate::p2p::persistence::{SyncStore, CHECKPOINT_WAL_THRESHOLD};
use crate::p2p::transport::{Transport, TransportEvent, WireMsg};
use crate::state::AppState;
use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
use iroh::{EndpointId, SecretKey};
use loro::{ExportMode, VersionVector};
use rand::RngCore;
use std::sync::Arc;
use std::time::Duration;
use tokio::sync::{broadcast, mpsc, Notify};
use tokio::time::interval;
use tokio_util::sync::CancellationToken;
use tokio_util::task::AbortOnDropHandle;
use tracing::{error, info, warn};
use zeroize::Zeroizing;

/// Periodic checkpoint cadence (design.md §9): the engine rewrites the
/// snapshot at most every `CHECKPOINT_INTERVAL`, and also opportunistically
/// when WAL entries exceed `CHECKPOINT_WAL_THRESHOLD`.
const CHECKPOINT_INTERVAL: Duration = Duration::from_secs(60);

/// Snapshot size that triggers a `p2p:warning` event on the
/// receiving Tauri app (T-022). Design.md §14 calls 50 MB out as
/// the soft limit before compaction becomes a real concern. The
/// warning is edge-triggered so the user doesn't see a toast every
/// minute once they're over.
const SNAPSHOT_WARNING_BYTES: u64 = 50 * 1_000_000;

pub struct SyncEngine {
    doc: Arc<SyncDoc>,
    store: Arc<SyncStore>,
    transport: Arc<Transport>,
    bridge: Arc<Bridge>,
    endpoint_id: EndpointId,

    cancel: CancellationToken,
    // Holding the loro Subscription keeps the local-update callback
    // registered; dropping the engine drops the subscription.
    _local_sub: loro::Subscription,
    _local_pump: AbortOnDropHandle<()>,
    _inbox_task: AbortOnDropHandle<()>,
    _checkpoint_task: AbortOnDropHandle<()>,
}

impl SyncEngine {
    /// Production entry point. Loads secrets from `app_state`, opens the
    /// on-disk SyncStore under `app_data_dir()/sync/`, brings up the
    /// transport, and spawns all background tasks.
    pub async fn start(state: Arc<AppState>) -> Result<Arc<Self>> {
        Self::start_with_bootstrap(state, Vec::new()).await
    }

    /// Like [`start`] but seeds the gossip transport with peers to
    /// dial proactively. Used by the QR-pairing joiner so it doesn't
    /// have to wait for relay-broadcast discovery before it can send
    /// `WireMsg::PairingRequest` to the seed.
    pub async fn start_with_bootstrap(
        state: Arc<AppState>,
        bootstrap_peers: Vec<EndpointId>,
    ) -> Result<Arc<Self>> {
        let (node_secret, doc_secret) = load_or_init_secrets(&state.pool).await?;

        let store = Arc::new(SyncStore::open(&state.app)?);
        let doc = Arc::new(SyncDoc::from_doc(store.load()?));
        let transport = Arc::new(
            Transport::start_with_bootstrap(node_secret, &doc_secret, bootstrap_peers).await?,
        );
        // Production wiring: Bridge::with_sql installs the Loro→SQLite
        // subscription so remote diffs land in the local DB and emit
        // matching Tauri events (T-010). The wrapping Arc<EventBus>
        // satisfies the BridgeEventSink trait object the bridge holds.
        let events: Arc<dyn crate::p2p::bridge::BridgeEventSink> =
            Arc::new(state.events.clone());
        let bridge = Bridge::with_sql(doc.clone(), state.pool.clone(), events);
        // Inject the live Brightspace client so the joiner-side of
        // BootstrapCredentials can call `store_credentials` directly.
        bridge.set_client(state.client.clone());

        Self::start_with_parts(store, doc, transport, bridge).await
    }

    /// Joiner-side QR-pairing entry point (T-013). Persists the
    /// `sync_doc_secret` carried in the QR, brings up the engine
    /// dialing the seed proactively, and broadcasts
    /// `WireMsg::PairingRequest { nonce }`. The seed verifies the
    /// nonce hasn't been consumed and replies with a `Snapshot`.
    ///
    /// The caller is expected to:
    ///   1. validate the QR via `pairing::consume_payload(&pool,
    ///      encoded)` first (rejects expired / replayed locally), then
    ///   2. call this with the resulting `PairingPayload`,
    ///   3. await the initial snapshot via
    ///      `engine.await_initial_snapshot(timeout).await?`,
    ///   4. run `engine.bridge().hydrate_from_doc().await?` to seed
    ///      SQLite from the freshly-imported Loro doc.
    ///
    /// The Tauri command `p2p_consume_pairing` (T-014) sequences all
    /// four steps so the React UI sees one async call.
    pub async fn pair_via_payload(
        state: Arc<AppState>,
        payload: &crate::p2p::pairing::PairingPayload,
    ) -> Result<Arc<Self>> {
        // Persist the shared secret BEFORE the engine starts so
        // load_or_init_secrets picks up this value rather than
        // generating a new random one. Goes through the same backend
        // (keychain primary, app_state fallback) so a re-pair lands
        // in the same place future loads will read from.
        crate::p2p::secrets::store(
            &state.pool,
            crate::p2p::secrets::SecretKind::SyncDocSecret,
            &payload.secret,
        )
        .await?;

        let seed: EndpointId = payload
            .node
            .parse()
            .map_err(|e| AppError::BadRequest(format!("pairing payload node id: {e}")))?;
        let engine = Self::start_with_bootstrap(state, vec![seed]).await?;

        // Send the pairing request now. Gossip won't have a neighbor
        // yet — the broadcast queues into the iroh send buffer and
        // ships once the dial completes (typically <1s in practice).
        engine
            .transport
            .broadcast(WireMsg::PairingRequest {
                nonce: payload.nonce.clone(),
            })
            .await?;

        Ok(engine)
    }

    /// Block until the first inbound `WireMsg::Snapshot` arrives, or
    /// `timeout` elapses. Used by the joiner after `pair_via_payload`
    /// to know it's safe to call `bridge.hydrate_from_doc()` — the
    /// hydration walk is meaningful only once the seed's snapshot has
    /// been imported.
    pub async fn await_initial_snapshot(&self, timeout: Duration) -> Result<()> {
        let mut rx = self.transport.subscribe();
        let waited = tokio::time::timeout(timeout, async {
            loop {
                match rx.recv().await {
                    Ok(TransportEvent::Message {
                        payload: WireMsg::Snapshot { .. },
                        ..
                    }) => return Ok::<(), AppError>(()),
                    Ok(_) => continue,
                    Err(broadcast::error::RecvError::Lagged(_)) => continue,
                    Err(broadcast::error::RecvError::Closed) => {
                        return Err(AppError::Other("transport inbox closed".into()));
                    }
                }
            }
        })
        .await;
        match waited {
            Ok(inner) => inner,
            Err(_) => Err(AppError::Other(format!(
                "no snapshot from seed within {}s",
                timeout.as_secs()
            ))),
        }
    }

    /// Test hook: caller has already built the parts (typically via the
    /// in-memory iroh test relay). Exposes the same task wiring as
    /// `start` without touching SQLite or `app_data_dir`.
    #[doc(hidden)]
    pub async fn start_with_parts(
        store: Arc<SyncStore>,
        doc: Arc<SyncDoc>,
        transport: Arc<Transport>,
        bridge: Arc<Bridge>,
    ) -> Result<Arc<Self>> {
        let endpoint_id = transport.endpoint_id();
        let cancel = CancellationToken::new();
        let checkpoint_notify = Arc::new(Notify::new());

        // -- local-update pump ---------------------------------------------
        // The Loro callback runs synchronously on the commit thread, so we
        // shovel each update onto an unbounded mpsc and let an async task
        // do the WAL write + broadcast. Unbounded is fine: commits are
        // user-paced (~1 per setter call), the consumer drains immediately,
        // and unbounded avoids any chance of blocking the commit hot path.
        let (local_tx, mut local_rx) = mpsc::unbounded_channel::<Vec<u8>>();
        let local_sub = doc.doc().subscribe_local_update(Box::new(move |bytes| {
            // send returns Err only if the receiver task has dropped,
            // which means the engine is shutting down — nothing to do.
            let _ = local_tx.send(bytes.clone());
            true
        }));

        let local_pump = AbortOnDropHandle::new(tokio::spawn({
            let store = store.clone();
            let transport = transport.clone();
            let cancel = cancel.clone();
            let notify = checkpoint_notify.clone();
            async move {
                loop {
                    let bytes = tokio::select! {
                        biased;
                        _ = cancel.cancelled() => break,
                        maybe = local_rx.recv() => match maybe {
                            Some(b) => b,
                            None => break,
                        },
                    };

                    if let Err(e) = store.append_update(&bytes) {
                        error!("wal append failed: {e}");
                    }
                    if store.pending_wal_entries() >= CHECKPOINT_WAL_THRESHOLD {
                        notify.notify_one();
                    }
                    if let Err(e) = transport
                        .broadcast(WireMsg::Update { bytes })
                        .await
                    {
                        // Broadcast failure is non-fatal — peers will resync
                        // via state-request when they reconnect.
                        warn!("local update broadcast failed: {e}");
                    }
                }
            }
        }));

        // -- inbox handler -------------------------------------------------
        let inbox_task = AbortOnDropHandle::new(tokio::spawn({
            let mut rx = transport.subscribe();
            let doc = doc.clone();
            let transport = transport.clone();
            let cancel = cancel.clone();
            // Pool is needed for the seed-side PairingRequest path
            // (consume_nonce against `consumed_pairing_nonces`). Tests
            // built via `Bridge::new` get None and skip nonce checks —
            // the gate is meaningful only when there's a real DB.
            let pool = bridge.pool().cloned();
            // Client is needed for the joiner-side BootstrapCredentials
            // path. Same story: tests skip, production has one.
            let client = bridge.client();
            async move {
                loop {
                    tokio::select! {
                        biased;
                        _ = cancel.cancelled() => break,
                        ev = rx.recv() => match ev {
                            Ok(TransportEvent::Message { from, payload }) => {
                                handle_inbound(
                                    &doc,
                                    &transport,
                                    pool.as_ref(),
                                    client.as_ref(),
                                    &from,
                                    payload,
                                )
                                .await;
                            }
                            Ok(TransportEvent::PeerConnected(id)) => {
                                info!("peer connected: {id}");
                            }
                            Ok(TransportEvent::PeerDisconnected(id)) => {
                                info!("peer disconnected: {id}");
                            }
                            Err(broadcast::error::RecvError::Lagged(n)) => {
                                warn!("inbox lagged {n} messages — state-sync will recover");
                            }
                            Err(broadcast::error::RecvError::Closed) => break,
                        }
                    }
                }
            }
        }));

        // -- checkpoint scheduler ------------------------------------------
        let checkpoint_task = AbortOnDropHandle::new(tokio::spawn({
            let store = store.clone();
            let doc = doc.clone();
            let cancel = cancel.clone();
            let notify = checkpoint_notify.clone();
            // Clone the events sink so we can emit p2p:warning when
            // the snapshot crosses 50 MB (T-022). None for tests
            // built via Bridge::new, which is fine — production has
            // a real EventBus and only production cares about UI
            // notifications anyway.
            let events = bridge.events().cloned();
            async move {
                let mut tick = interval(CHECKPOINT_INTERVAL);
                // Consume the immediate first tick so we don't checkpoint
                // an empty WAL the moment we boot.
                tick.tick().await;
                // Edge-triggered warning: only fire on the transition
                // from <50 MB to >=50 MB, so the user doesn't see a
                // toast every 60s once they're over.
                let mut last_was_oversized = false;
                loop {
                    tokio::select! {
                        biased;
                        _ = cancel.cancelled() => break,
                        _ = tick.tick() => {}
                        _ = notify.notified() => {}
                    }
                    if store.pending_wal_entries() == 0 {
                        continue;
                    }
                    if let Err(e) = store.checkpoint(&doc.doc()) {
                        error!("checkpoint failed: {e}");
                        continue;
                    }
                    let stats = store.storage_stats();
                    let oversized = stats.snapshot_bytes > SNAPSHOT_WARNING_BYTES;
                    if oversized && !last_was_oversized {
                        if let Some(events) = &events {
                            events.p2p_warning(&format!(
                                "Sync snapshot is {} MB — consider rotating the secret to start fresh.",
                                stats.snapshot_bytes / 1_000_000
                            ));
                        }
                    }
                    last_was_oversized = oversized;
                }
            }
        }));

        info!("sync engine started: endpoint_id={endpoint_id}");

        Ok(Arc::new(Self {
            doc,
            store,
            transport,
            bridge,
            endpoint_id,
            cancel,
            _local_sub: local_sub,
            _local_pump: local_pump,
            _inbox_task: inbox_task,
            _checkpoint_task: checkpoint_task,
        }))
    }

    pub fn endpoint_id(&self) -> EndpointId {
        self.endpoint_id
    }

    pub fn doc(&self) -> Arc<SyncDoc> {
        self.doc.clone()
    }

    pub fn store(&self) -> Arc<SyncStore> {
        self.store.clone()
    }

    pub fn transport(&self) -> Arc<Transport> {
        self.transport.clone()
    }

    pub fn bridge(&self) -> Arc<Bridge> {
        self.bridge.clone()
    }

    /// Force a checkpoint immediately. Called on graceful shutdown.
    pub fn checkpoint_now(&self) -> Result<()> {
        self.store.checkpoint(&self.doc.doc())
    }

    /// Cancel all background tasks and force a final checkpoint. Returns
    /// the held Transport so the caller can `transport.shutdown().await`
    /// — Transport::shutdown takes `self`, which doesn't compose with
    /// the Arc<Transport> lifetime here.
    pub async fn shutdown(&self) -> Result<()> {
        self.cancel.cancel();
        if let Err(e) = self.checkpoint_now() {
            warn!("final checkpoint failed: {e}");
        }
        Ok(())
    }
}

async fn handle_inbound(
    doc: &SyncDoc,
    transport: &Transport,
    pool: Option<&sqlx::SqlitePool>,
    client: Option<&Arc<crate::client::BrightspaceClient>>,
    from: &str,
    msg: WireMsg,
) {
    match msg {
        WireMsg::Update { bytes } | WireMsg::Snapshot { bytes } => {
            if let Err(e) = doc.doc().import(&bytes) {
                warn!("inbound import from {from} failed: {e}");
            }
        }
        WireMsg::StateRequest { vv: their_vv_bytes } => {
            let their_vv = match VersionVector::decode(&their_vv_bytes) {
                Ok(v) => v,
                Err(e) => {
                    warn!("malformed state vector from {from}: {e}");
                    return;
                }
            };
            let our_vv_bytes = doc.doc().oplog_vv().encode();
            let bytes = match doc.doc().export(ExportMode::updates(&their_vv)) {
                Ok(b) => b,
                Err(e) => {
                    warn!("export updates_since failed: {e}");
                    return;
                }
            };
            let response = WireMsg::StateResponse { vv: our_vv_bytes, bytes };
            if let Err(e) = transport.broadcast(response).await {
                warn!("state response broadcast to {from} failed: {e}");
            }
        }
        WireMsg::StateResponse { bytes, .. } => {
            if let Err(e) = doc.doc().import(&bytes) {
                warn!("state response import from {from} failed: {e}");
            }
        }
        WireMsg::PairingRequest { nonce } => {
            // Seed-side: gate on the nonce table. If the joiner is
            // legitimate (first use of this QR), record the nonce and
            // reply with a full snapshot. If the nonce is missing
            // (test wiring with `Bridge::new`), skip the gate but
            // still reply — that lets the integration test exercise
            // the snapshot path without bringing up a real DB.
            if let Some(pool) = pool {
                if let Err(e) = crate::p2p::pairing::consume_nonce(pool, &nonce).await {
                    warn!("rejecting pairing request from {from}: {e}");
                    return;
                }
            }
            let bytes = match doc.doc().export(loro::ExportMode::Snapshot) {
                Ok(b) => b,
                Err(e) => {
                    warn!("snapshot export for {from} failed: {e}");
                    return;
                }
            };
            if let Err(e) = transport.broadcast(WireMsg::Snapshot { bytes }).await {
                warn!("pairing snapshot broadcast to {from} failed: {e}");
                return;
            }
            // One-shot credential bootstrap so the joining device (often
            // a fresh iOS install with no way to drive Brightspace
            // sign-in) can skip first-time login. Sent after the
            // snapshot so the joiner already has its overlay data
            // imported by the time the credentials land. No-op if the
            // seed itself isn't authenticated, or if we lack a pool
            // (test wiring).
            if let Some(pool) = pool {
                match fetch_bootstrap_credentials(pool).await {
                    Ok(Some(creds)) => {
                        if let Err(e) = transport.broadcast(creds).await {
                            warn!("bootstrap credentials broadcast to {from} failed: {e}");
                        }
                    }
                    Ok(None) => {
                        // Seed not authenticated — silently skip. Joiner
                        // will fall back to the manual sign-in flow.
                    }
                    Err(e) => warn!("read bootstrap credentials failed: {e}"),
                }
            }
        }
        WireMsg::BootstrapCredentials { host, cookie, uid, user_id } => {
            // Joiner-side: persist the seed's session if (and only if)
            // we don't already have one. The "no clobber" check makes
            // re-pairing safe and prevents a stale paired device from
            // overwriting a freshly-rotated cookie on this one.
            let Some(client) = client else {
                warn!("ignoring BootstrapCredentials: no client wired");
                return;
            };
            let Some(pool) = pool else {
                warn!("ignoring BootstrapCredentials: no pool wired");
                return;
            };
            if client.is_configured() {
                tracing::debug!(
                    "ignoring BootstrapCredentials from {from}: already authenticated"
                );
                return;
            }
            match client
                .store_credentials(
                    pool,
                    &host,
                    &cookie,
                    uid.as_deref(),
                    user_id.as_deref(),
                )
                .await
            {
                Ok(()) => {
                    tracing::info!(
                        "adopted Brightspace credentials from paired device ({})",
                        from
                    );
                    // Same app-event the desktop login flow emits on
                    // success; the React layer already listens for it
                    // and refreshes auth status / kicks off a sync.
                    let _ = client.emit_auth_captured(&host);
                }
                Err(e) => warn!("store_credentials from {from} failed: {e}"),
            }
        }
    }
}

/// Read the seed's current Brightspace credentials out of
/// `user_preferences` for a `BootstrapCredentials` push. Returns
/// `Ok(None)` if the seed isn't currently authenticated, so the seed
/// can quietly skip the push for that joiner.
async fn fetch_bootstrap_credentials(
    pool: &sqlx::SqlitePool,
) -> Result<Option<WireMsg>> {
    let row: Option<(
        Option<String>,
        Option<String>,
        Option<String>,
        Option<String>,
    )> = sqlx::query_as(
        "SELECT brightspace_host, brightspace_cookie, brightspace_uid, brightspace_user_id \
         FROM user_preferences LIMIT 1",
    )
    .fetch_optional(pool)
    .await?;
    let Some((Some(host), Some(cookie), uid, user_id)) = row else {
        return Ok(None);
    };
    if host.trim().is_empty() || cookie.trim().is_empty() {
        return Ok(None);
    }
    Ok(Some(WireMsg::BootstrapCredentials {
        host,
        cookie,
        uid,
        user_id,
    }))
}

/// Read the iroh node secret + shared sync_doc_secret, generating
/// and persisting either if missing.
///
/// On-disk format:
///   - `iroh_node_secret`: base64 of the 32-byte ed25519 secret bytes
///   - `sync_doc_secret`:  hex of the 32 raw bytes (matches the QR
///                          payload format from T-012 / design.md §6)
///
/// Storage: `crate::p2p::secrets` reads the OS keychain first and
/// falls back to the SQLite `app_state` table on systems without
/// keychain support (T-021). Existing pre-T-021 installs are
/// migrated transparently — `migrate_to_keychain` runs
/// unconditionally before the first load so a SQLite-only secret
/// moves into the keychain on the next start.
///
/// `sync_doc_secret` is wrapped in `Zeroizing` so the raw 32 bytes
/// get scrubbed from RAM on drop.
async fn load_or_init_secrets(
    pool: &sqlx::SqlitePool,
) -> Result<(SecretKey, Zeroizing<Vec<u8>>)> {
    use crate::p2p::secrets::{self, SecretKind};
    secrets::migrate_to_keychain(pool, SecretKind::IrohNodeSecret).await?;
    secrets::migrate_to_keychain(pool, SecretKind::SyncDocSecret).await?;

    let node_secret = match secrets::load(pool, SecretKind::IrohNodeSecret).await? {
        Some(s) => {
            let raw = B64
                .decode(s.as_bytes())
                .map_err(|e| AppError::Other(format!("decode iroh_node_secret: {e}")))?;
            let arr: [u8; 32] = raw
                .as_slice()
                .try_into()
                .map_err(|_| AppError::Other("iroh_node_secret length != 32".into()))?;
            SecretKey::from_bytes(&arr)
        }
        None => {
            let key = SecretKey::generate();
            let encoded = B64.encode(key.to_bytes());
            secrets::store(pool, SecretKind::IrohNodeSecret, &encoded).await?;
            key
        }
    };

    let doc_secret = match secrets::load(pool, SecretKind::SyncDocSecret).await? {
        Some(s) => {
            let raw = hex::decode(&s)
                .map_err(|e| AppError::Other(format!("decode sync_doc_secret: {e}")))?;
            if raw.len() != 32 {
                return Err(AppError::Other("sync_doc_secret length != 32".into()));
            }
            Zeroizing::new(raw)
        }
        None => {
            let mut buf = vec![0u8; 32];
            rand::thread_rng().fill_bytes(&mut buf);
            let encoded = hex::encode(&buf);
            secrets::store(pool, SecretKind::SyncDocSecret, &encoded).await?;
            Zeroizing::new(buf)
        }
    };

    Ok((node_secret, doc_secret))
}

/// Generic key/value read on `app_state`. Public so the pairing-related
/// commands (and T-022's storage stats) can share one well-known
/// helper rather than each rolling its own SELECT.
pub async fn get_app_state(pool: &sqlx::SqlitePool, key: &str) -> Result<Option<String>> {
    let row: Option<(Option<String>,)> =
        sqlx::query_as("SELECT value FROM app_state WHERE key = ?")
            .bind(key)
            .fetch_optional(pool)
            .await?;
    Ok(row.and_then(|(v,)| v))
}

pub async fn set_app_state(pool: &sqlx::SqlitePool, key: &str, value: &str) -> Result<()> {
    sqlx::query(
        "INSERT INTO app_state (key, value, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP) \
         ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP",
    )
    .bind(key)
    .bind(value)
    .execute(pool)
    .await?;
    Ok(())
}

// ---- Tests ----------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use iroh::{
        address_lookup::memory::MemoryLookup,
        endpoint::presets::Minimal,
        tls::CaRootsConfig,
        Endpoint, EndpointAddr, RelayMap, RelayMode,
    };
    use iroh_gossip::net::GOSSIP_ALPN;
    use std::time::Duration;
    use tempfile::TempDir;
    use tokio::time::timeout;

    /// Build an iroh endpoint configured for the in-memory test relay.
    /// Mirrors the helper in `transport.rs` so engine tests stay
    /// self-contained.
    async fn build_test_endpoint(relay_map: RelayMap) -> Endpoint {
        Endpoint::builder(Minimal)
            .secret_key(SecretKey::generate())
            .alpns(vec![GOSSIP_ALPN.to_vec()])
            .relay_mode(RelayMode::Custom(relay_map))
            .ca_roots_config(CaRootsConfig::insecure_skip_verify())
            .bind()
            .await
            .unwrap()
    }

    fn store_in(tmp: &TempDir, name: &str) -> Arc<SyncStore> {
        Arc::new(SyncStore::open_at(tmp.path().join(name)).unwrap())
    }

    /// T-008 acceptance: start engine, mutate doc, shut down, restart,
    /// mutations are still present AND were broadcast to a peer engine
    /// during the first run.
    #[tokio::test]
    async fn engine_persists_and_broadcasts_mutations() {
        let (relay_map, relay_url, _relay_guard) =
            iroh::test_utils::run_relay_server().await.unwrap();
        let memory_lookup = MemoryLookup::new();

        let tmp = TempDir::new().unwrap();
        let store_a = store_in(&tmp, "a");
        let store_b = store_in(&tmp, "b");

        let body = async {
            // -- bring up two endpoints + cross-register addresses --------
            let ep_a = build_test_endpoint(relay_map.clone()).await;
            let ep_b = build_test_endpoint(relay_map.clone()).await;
            ep_a.address_lookup().unwrap().add(memory_lookup.clone());
            ep_b.address_lookup().unwrap().add(memory_lookup.clone());
            ep_a.online().await;
            ep_b.online().await;
            let id_a = ep_a.id();
            let id_b = ep_b.id();
            memory_lookup
                .add_endpoint_info(EndpointAddr::new(id_a).with_relay_url(relay_url.clone()));
            memory_lookup
                .add_endpoint_info(EndpointAddr::new(id_b).with_relay_url(relay_url.clone()));

            // -- bring up two transports on the same shared secret -------
            let secret = b"engine-test-shared-secret-aabb";
            let transport_a =
                Arc::new(Transport::start_with_endpoint(ep_a, secret, vec![]).await.unwrap());
            let transport_b =
                Arc::new(Transport::start_with_endpoint(ep_b, secret, vec![id_a]).await.unwrap());

            // -- bring up engine A (the one we'll mutate, then restart) --
            let doc_a = Arc::new(SyncDoc::from_doc(store_a.load().unwrap()));
            let engine_a = SyncEngine::start_with_parts(
                store_a.clone(),
                doc_a.clone(),
                transport_a.clone(),
                Bridge::new(doc_a.clone()),
            )
            .await
            .unwrap();

            // -- bring up engine B (the receiver) ------------------------
            let doc_b = Arc::new(SyncDoc::from_doc(store_b.load().unwrap()));
            let engine_b = SyncEngine::start_with_parts(
                store_b.clone(),
                doc_b.clone(),
                transport_b.clone(),
                Bridge::new(doc_b.clone()),
            )
            .await
            .unwrap();

            // Wait for the gossip mesh to form before mutating; otherwise
            // the broadcast can race ahead of the join and B never sees it.
            let mut rx_a = transport_a.subscribe();
            let mut rx_b = transport_b.subscribe();
            let join = async {
                let mut a_joined = false;
                let mut b_joined = false;
                while !(a_joined && b_joined) {
                    tokio::select! {
                        ev = rx_a.recv(), if !a_joined => {
                            if let Ok(TransportEvent::PeerConnected(_)) = ev { a_joined = true; }
                        }
                        ev = rx_b.recv(), if !b_joined => {
                            if let Ok(TransportEvent::PeerConnected(_)) = ev { b_joined = true; }
                        }
                    }
                }
            };
            timeout(Duration::from_secs(15), join)
                .await
                .expect("peers did not join in time");

            // -- mutate on A and assert it propagates to B ---------------
            doc_a.set_pref_display_name("Alice").unwrap();
            doc_a
                .set_course_overlay(
                    "12345",
                    crate::p2p::doc::CourseField::IsPinned(true),
                )
                .unwrap();

            let observed = timeout(Duration::from_secs(5), async {
                loop {
                    if doc_b.get_pref_display_name().as_deref() == Some("Alice")
                        && doc_b
                            .get_course_overlay("12345")
                            .and_then(|c| c.is_pinned)
                            == Some(true)
                    {
                        return ();
                    }
                    tokio::time::sleep(Duration::from_millis(50)).await;
                }
            })
            .await;
            assert!(observed.is_ok(), "engine B did not receive A's mutations within 5s");

            // -- shut down A; force its checkpoint -----------------------
            engine_a.shutdown().await.unwrap();
            engine_b.shutdown().await.unwrap();
            drop(engine_a);
            drop(engine_b);
            // Drop transports too so the next iteration can rebind.
            drop(transport_a);
            drop(transport_b);
            drop(doc_a);
            drop(doc_b);
        };

        timeout(Duration::from_secs(45), body)
            .await
            .expect("engine integration test exceeded 45s");

        // -- restart engine A from the same on-disk store ----------------
        // The transport doesn't matter for this assertion — we're proving
        // the WAL/snapshot survived, which is purely a SyncStore concern.
        let reloaded = SyncDoc::from_doc(store_a.load().unwrap());
        assert_eq!(reloaded.get_pref_display_name().as_deref(), Some("Alice"));
        assert_eq!(
            reloaded.get_course_overlay("12345").and_then(|c| c.is_pinned),
            Some(true),
        );
    }

    /// Force the checkpoint scheduler to fire via the WAL-threshold
    /// notify path: append more than `CHECKPOINT_WAL_THRESHOLD` updates
    /// and confirm the snapshot file shows up + the WAL counter resets.
    /// Skips the transport entirely — pure local-update plumbing test.
    #[tokio::test]
    async fn engine_checkpoints_when_wal_threshold_crossed() {
        let (relay_map, _relay_url, _relay_guard) =
            iroh::test_utils::run_relay_server().await.unwrap();
        let tmp = TempDir::new().unwrap();
        let store = store_in(&tmp, "x");
        let doc = Arc::new(SyncDoc::from_doc(store.load().unwrap()));

        // We still need a real Transport to satisfy start_with_parts;
        // a single self-loop endpoint is enough since we never expect
        // a peer.
        let ep = build_test_endpoint(relay_map.clone()).await;
        let transport = Arc::new(
            Transport::start_with_endpoint(ep, b"isolated-engine-secret", vec![])
                .await
                .unwrap(),
        );

        let engine = SyncEngine::start_with_parts(
            store.clone(),
            doc.clone(),
            transport.clone(),
            Bridge::new(doc.clone()),
        )
        .await
        .unwrap();

        // Drive a few past the threshold so the local-update pump kicks
        // the checkpoint notify.
        for i in 0..(CHECKPOINT_WAL_THRESHOLD + 5) {
            doc.set_assignment_overlay(
                &format!("100:{i}"),
                crate::p2p::doc::AssignmentField::Completed(true),
            )
            .unwrap();
        }

        // Wait for the scheduler to wake on the notify and drain.
        let drained = timeout(Duration::from_secs(5), async {
            loop {
                if store.pending_wal_entries() == 0 {
                    return ();
                }
                tokio::time::sleep(Duration::from_millis(50)).await;
            }
        })
        .await;
        assert!(drained.is_ok(), "checkpoint did not fire after threshold");

        engine.shutdown().await.unwrap();
    }

    /// T-013 acceptance: two engines on the in-memory iroh test relay.
    /// Seed has data; joiner sends `WireMsg::PairingRequest { nonce }`;
    /// seed consumes nonce + replies with `Snapshot`; joiner awaits
    /// the snapshot and runs `bridge.hydrate_from_doc()`. Joiner's
    /// SQLite must mirror the seed's class-B state within 5s.
    ///
    /// Also asserts the replay defense: a second PairingRequest with
    /// the same nonce is rejected by the seed (the joiner times out
    /// waiting for a second Snapshot).
    #[tokio::test]
    async fn pairing_handshake_seeds_joiner_with_full_state() {
        use crate::p2p::bridge::{BridgeEventSink, OverlayKind};
        use crate::p2p::pairing::{self, PairingPayload};
        use sqlx::sqlite::SqlitePoolOptions;

        // ---- shared iroh test infra ---------------------------------------
        let (relay_map, relay_url, _relay_guard) =
            iroh::test_utils::run_relay_server().await.unwrap();
        let memory_lookup = MemoryLookup::new();

        let body = async {
            let ep_seed = build_test_endpoint(relay_map.clone()).await;
            let ep_join = build_test_endpoint(relay_map.clone()).await;
            ep_seed.address_lookup().unwrap().add(memory_lookup.clone());
            ep_join.address_lookup().unwrap().add(memory_lookup.clone());
            ep_seed.online().await;
            ep_join.online().await;
            let id_seed = ep_seed.id();
            let id_join = ep_join.id();
            memory_lookup
                .add_endpoint_info(EndpointAddr::new(id_seed).with_relay_url(relay_url.clone()));
            memory_lookup
                .add_endpoint_info(EndpointAddr::new(id_join).with_relay_url(relay_url.clone()));

            // ---- two SQLite pools (with all migrations) -------------------
            // The seed's pool is what consume_nonce writes to. Both pools
            // need the courses table for hydrate to land overlays.
            async fn build_pool() -> sqlx::SqlitePool {
                let pool = SqlitePoolOptions::new()
                    .max_connections(1)
                    .connect("sqlite::memory:")
                    .await
                    .unwrap();
                sqlx::migrate!("./migrations").run(&pool).await.unwrap();
                sqlx::query("INSERT INTO user_preferences (api_port) VALUES (4567)")
                    .execute(&pool)
                    .await
                    .unwrap();
                pool
            }
            let pool_seed = build_pool().await;
            let pool_join = build_pool().await;

            // Pre-populate the seed's underlying course rows so apply_remote
            // (when the seed's overlays land on the joiner side) has rows
            // to UPDATE — for course IDs that don't exist on the joiner,
            // hydrate would defer; this test asserts the immediate-update
            // path. T-011 already covers the deferred case.
            sqlx::query(
                "INSERT INTO courses (org_unit_id, name, is_pinned) VALUES \
                 ('111', 'Course A', 0), ('222', 'Course B', 0)",
            )
            .execute(&pool_join)
            .await
            .unwrap();

            // ---- seed engine (Bridge with SQL so consume_nonce has a DB) -
            #[derive(Default)]
            struct NopSink;
            impl BridgeEventSink for NopSink {
                fn course_updated(&self, _: &str) {}
                fn assignments_updated(&self) {}
                fn grades_updated(&self) {}
                fn notifications_updated(&self) {}
                fn prefs_updated(&self) {}
            }
            let sink_seed: Arc<dyn BridgeEventSink> = Arc::new(NopSink);
            let sink_join: Arc<dyn BridgeEventSink> = Arc::new(NopSink);

            let tmp = TempDir::new().unwrap();
            let store_seed = store_in(&tmp, "seed");
            let store_join = store_in(&tmp, "join");

            let secret = b"pairing-handshake-shared-secret";
            let transport_seed = Arc::new(
                Transport::start_with_endpoint(ep_seed, secret, vec![]).await.unwrap(),
            );
            let transport_join = Arc::new(
                Transport::start_with_endpoint(ep_join, secret, vec![id_seed])
                    .await
                    .unwrap(),
            );

            let doc_seed = Arc::new(SyncDoc::from_doc(store_seed.load().unwrap()));
            let bridge_seed = Bridge::with_sql(
                doc_seed.clone(),
                pool_seed.clone(),
                sink_seed.clone(),
            );
            let engine_seed = SyncEngine::start_with_parts(
                store_seed.clone(),
                doc_seed.clone(),
                transport_seed.clone(),
                bridge_seed.clone(),
            )
            .await
            .unwrap();

            let doc_join = Arc::new(SyncDoc::from_doc(store_join.load().unwrap()));
            let bridge_join = Bridge::with_sql(
                doc_join.clone(),
                pool_join.clone(),
                sink_join.clone(),
            );
            let engine_join = SyncEngine::start_with_parts(
                store_join.clone(),
                doc_join.clone(),
                transport_join.clone(),
                bridge_join.clone(),
            )
            .await
            .unwrap();

            // ---- seed populates some Class-B state ------------------------
            doc_seed.set_pref_display_name("Tucker").unwrap();
            doc_seed
                .set_course_overlay("111", crate::p2p::doc::CourseField::IsPinned(true))
                .unwrap();
            doc_seed
                .set_course_overlay(
                    "222",
                    crate::p2p::doc::CourseField::CustomColor(Some("#0099ff".into())),
                )
                .unwrap();
            // A composite-key overlay whose underlying assignment row
            // doesn't exist on the joiner — should land in pending.
            doc_seed
                .set_assignment_overlay(
                    "777:abc",
                    crate::p2p::doc::AssignmentField::Completed(true),
                )
                .unwrap();

            // ---- wait for gossip mesh formation ---------------------------
            let mut rx_seed = transport_seed.subscribe();
            let mut rx_join = transport_join.subscribe();
            let join_mesh = async {
                let mut s = false;
                let mut j = false;
                while !(s && j) {
                    tokio::select! {
                        ev = rx_seed.recv(), if !s => {
                            if let Ok(TransportEvent::PeerConnected(_)) = ev { s = true; }
                        }
                        ev = rx_join.recv(), if !j => {
                            if let Ok(TransportEvent::PeerConnected(_)) = ev { j = true; }
                        }
                    }
                }
            };
            timeout(Duration::from_secs(15), join_mesh)
                .await
                .expect("pairing test: peers did not join in time");

            // ---- joiner sends PairingRequest -------------------------------
            // Construct a PairingPayload purely for its nonce + secret_hex
            // — the wire-level handshake only consumes those. The QR/scan
            // surface (start_with_bootstrap) is exercised by T-014.
            let payload = PairingPayload::new(
                id_seed.to_string(),
                vec![],
                Some(relay_url.to_string()),
                hex::encode(secret),
            );
            transport_join
                .broadcast(WireMsg::PairingRequest {
                    nonce: payload.nonce.clone(),
                })
                .await
                .unwrap();

            // ---- joiner awaits the seed's Snapshot reply -------------------
            engine_join
                .await_initial_snapshot(Duration::from_secs(5))
                .await
                .expect("joiner did not receive snapshot from seed");

            // ---- joiner runs hydrate_from_doc; assert SQLite mirrored -----
            engine_join.bridge().hydrate_from_doc().await.unwrap();

            let pref: (Option<String>,) =
                sqlx::query_as("SELECT display_name FROM user_preferences LIMIT 1")
                    .fetch_one(&pool_join)
                    .await
                    .unwrap();
            assert_eq!(pref.0.as_deref(), Some("Tucker"));

            let row111: (i64,) =
                sqlx::query_as("SELECT is_pinned FROM courses WHERE org_unit_id = '111'")
                    .fetch_one(&pool_join)
                    .await
                    .unwrap();
            assert_eq!(row111.0, 1);

            let row222: (Option<String>,) = sqlx::query_as(
                "SELECT custom_color FROM courses WHERE org_unit_id = '222'",
            )
            .fetch_one(&pool_join)
            .await
            .unwrap();
            assert_eq!(row222.0.as_deref(), Some("#0099ff"));

            // The composite-key overlay should be parked in pending.
            let pending: (i64,) = sqlx::query_as(
                "SELECT COUNT(*) FROM pending_overlay_apply \
                 WHERE kind = 'assignment' AND key = '777:abc'",
            )
            .fetch_one(&pool_join)
            .await
            .unwrap();
            assert_eq!(pending.0, 1);

            // ---- replay defense: second PairingRequest with same nonce ---
            // Seed should reject (consume_nonce returns BadRequest), so no
            // second Snapshot is broadcast. Joiner times out.
            transport_join
                .broadcast(WireMsg::PairingRequest {
                    nonce: payload.nonce.clone(),
                })
                .await
                .unwrap();
            let replay_result = engine_join
                .await_initial_snapshot(Duration::from_millis(500))
                .await;
            assert!(
                replay_result.is_err(),
                "replay must be rejected by seed (no second snapshot)"
            );
            let count: (i64,) = sqlx::query_as(
                "SELECT COUNT(*) FROM consumed_pairing_nonces WHERE nonce = ?",
            )
            .bind(&payload.nonce)
            .fetch_one(&pool_seed)
            .await
            .unwrap();
            assert_eq!(count.0, 1, "nonce must be recorded exactly once");

            // Reference unused-but-needed values for the borrow checker.
            let _ = id_join;
            let _ = bridge_seed;
            let _ = bridge_join;
            let _ = pairing::PAIRING_VERSION;
            let _ = OverlayKind::Course;

            engine_seed.shutdown().await.unwrap();
            engine_join.shutdown().await.unwrap();
        };

        timeout(Duration::from_secs(45), body)
            .await
            .expect("pairing handshake test exceeded 45s");
    }

    /// T-023 acceptance: three engines, all on the same in-memory iroh
    /// test relay, fire concurrent edits across overlapping keys, and
    /// must converge to identical Loro docs within a bounded window.
    /// Lives in this module rather than the ticket's suggested
    /// `tests/p2p_three_way.rs` because all the iroh + relay test
    /// helpers (`build_test_endpoint`, `store_in`, MemoryLookup wiring)
    /// live in `engine::tests` and exposing them as `pub(crate)` just
    /// to share with an integration test would be churn for no win.
    ///
    /// Convergence criterion: every pair of (doc_a, doc_b) imports
    /// each other's all_updates and ends up at the same oplog VV.
    /// This is the strongest single check — Loro guarantees identical
    /// state if VVs match across two replicas. (We do that
    /// post-import rather than relying on gossip catching up to a
    /// quiescent point, which would race on slow CI.)
    #[tokio::test]
    async fn three_engines_converge_under_concurrent_writes() {
        let (relay_map, relay_url, _relay_guard) =
            iroh::test_utils::run_relay_server().await.unwrap();
        let memory_lookup = MemoryLookup::new();

        let body = async {
            // ---- three endpoints + cross-registered addresses ------------
            let ep_a = build_test_endpoint(relay_map.clone()).await;
            let ep_b = build_test_endpoint(relay_map.clone()).await;
            let ep_c = build_test_endpoint(relay_map.clone()).await;
            for ep in [&ep_a, &ep_b, &ep_c] {
                ep.address_lookup().unwrap().add(memory_lookup.clone());
                ep.online().await;
            }
            let id_a = ep_a.id();
            let id_b = ep_b.id();
            let id_c = ep_c.id();
            for id in [id_a, id_b, id_c] {
                memory_lookup.add_endpoint_info(
                    EndpointAddr::new(id).with_relay_url(relay_url.clone()),
                );
            }

            // ---- three transports on a shared secret ---------------------
            // A is the seed (no bootstrap); B and C dial A.
            let secret = b"three-way-shared-doc-secret";
            let transport_a = Arc::new(
                Transport::start_with_endpoint(ep_a, secret, vec![]).await.unwrap(),
            );
            let transport_b = Arc::new(
                Transport::start_with_endpoint(ep_b, secret, vec![id_a]).await.unwrap(),
            );
            let transport_c = Arc::new(
                Transport::start_with_endpoint(ep_c, secret, vec![id_a]).await.unwrap(),
            );

            // ---- three engines (Bridge::new — no SQL needed for this
            //      test; we're checking Loro convergence, not SQLite
            //      mirroring, which is covered by T-010's tests) -----
            let tmp = TempDir::new().unwrap();
            let store_a = store_in(&tmp, "three_a");
            let store_b = store_in(&tmp, "three_b");
            let store_c = store_in(&tmp, "three_c");

            let doc_a = Arc::new(SyncDoc::from_doc(store_a.load().unwrap()));
            let doc_b = Arc::new(SyncDoc::from_doc(store_b.load().unwrap()));
            let doc_c = Arc::new(SyncDoc::from_doc(store_c.load().unwrap()));

            let engine_a = SyncEngine::start_with_parts(
                store_a.clone(),
                doc_a.clone(),
                transport_a.clone(),
                Bridge::new(doc_a.clone()),
            )
            .await
            .unwrap();
            let engine_b = SyncEngine::start_with_parts(
                store_b.clone(),
                doc_b.clone(),
                transport_b.clone(),
                Bridge::new(doc_b.clone()),
            )
            .await
            .unwrap();
            let engine_c = SyncEngine::start_with_parts(
                store_c.clone(),
                doc_c.clone(),
                transport_c.clone(),
                Bridge::new(doc_c.clone()),
            )
            .await
            .unwrap();

            // ---- wait for the three-way mesh to form ---------------------
            // Each transport sees PeerConnected for at least one other.
            // Without this, an early write can race the gossip join and
            // never reach the laggard.
            let mut rxs = [
                transport_a.subscribe(),
                transport_b.subscribe(),
                transport_c.subscribe(),
            ];
            let mesh = async {
                let mut joined = [false; 3];
                while !joined.iter().all(|&v| v) {
                    for (i, rx) in rxs.iter_mut().enumerate() {
                        if joined[i] {
                            continue;
                        }
                        if let Ok(TransportEvent::PeerConnected(_)) = rx.recv().await {
                            joined[i] = true;
                        }
                    }
                }
            };
            timeout(Duration::from_secs(20), mesh)
                .await
                .expect("three-way mesh did not form in time");

            // ---- concurrent writes ---------------------------------------
            // 30 keys overlapping across all three peers — the
            // overlapping ones exercise CRDT merge specifically, the
            // disjoint ones exercise the broadcast plumbing.
            //
            // We pace via tokio::yield_now() rather than sleep so the
            // test runs in <1s rather than the design's 30s; the
            // engine's pump path is the same either way.
            for i in 0..30 {
                let key = format!("100:{i}");
                let val = i % 2 == 0;
                doc_a
                    .set_assignment_overlay(
                        &key,
                        crate::p2p::doc::AssignmentField::Completed(val),
                    )
                    .unwrap();
                tokio::task::yield_now().await;
            }
            for i in 10..40 {
                doc_b
                    .set_course_overlay(
                        &format!("course-{i}"),
                        crate::p2p::doc::CourseField::IsPinned(i % 3 == 0),
                    )
                    .unwrap();
                tokio::task::yield_now().await;
            }
            for i in 20..50 {
                doc_c
                    .set_pref_semester_color(
                        &format!("sem-{i}"),
                        &format!("#{:06x}", i * 17_777),
                    )
                    .unwrap();
                tokio::task::yield_now().await;
            }
            // Throw in a few overlapping writes to force the merge.
            doc_a.set_pref_display_name("Alice").unwrap();
            doc_b.set_pref_display_name("Bob").unwrap();
            doc_c.set_pref_display_name("Carol").unwrap();

            // ---- wait for gossip to settle, then reconcile ---------------
            // Give gossip a window to deliver everything, then
            // explicitly cross-import all_updates pairwise — same
            // pattern as the existing two-doc convergence test.
            // This lets us assert convergence with bounded latency
            // even on a flaky CI gossip path: as long as the engines
            // ran long enough, the convergence is deterministic.
            tokio::time::sleep(Duration::from_millis(800)).await;

            for _round in 0..3 {
                let updates_a = doc_a
                    .doc()
                    .export(loro::ExportMode::all_updates())
                    .unwrap();
                let updates_b = doc_b
                    .doc()
                    .export(loro::ExportMode::all_updates())
                    .unwrap();
                let updates_c = doc_c
                    .doc()
                    .export(loro::ExportMode::all_updates())
                    .unwrap();
                doc_b.doc().import(&updates_a).unwrap();
                doc_c.doc().import(&updates_a).unwrap();
                doc_a.doc().import(&updates_b).unwrap();
                doc_c.doc().import(&updates_b).unwrap();
                doc_a.doc().import(&updates_c).unwrap();
                doc_b.doc().import(&updates_c).unwrap();
            }

            // ---- assert convergence --------------------------------------
            let vv_a = doc_a.doc().oplog_vv().encode();
            let vv_b = doc_b.doc().oplog_vv().encode();
            let vv_c = doc_c.doc().oplog_vv().encode();
            assert_eq!(vv_a, vv_b, "A and B must converge to the same oplog VV");
            assert_eq!(vv_a, vv_c, "A and C must converge to the same oplog VV");

            // Spot-check a handful of keys: each device sees the
            // canonical merged state for fields written by another.
            assert_eq!(
                doc_a
                    .get_assignment_overlay("100:5")
                    .unwrap()
                    .completed,
                Some(false),
            );
            assert_eq!(
                doc_b
                    .get_assignment_overlay("100:5")
                    .unwrap()
                    .completed,
                Some(false),
            );
            assert_eq!(
                doc_c
                    .get_assignment_overlay("100:5")
                    .unwrap()
                    .completed,
                Some(false),
            );

            // Display name is contended — the merged value must be
            // identical across all three, even if exact contents
            // depend on Loro's RGA tiebreak.
            let name_a = doc_a.get_pref_display_name();
            let name_b = doc_b.get_pref_display_name();
            let name_c = doc_c.get_pref_display_name();
            assert_eq!(name_a, name_b);
            assert_eq!(name_a, name_c);
            assert!(name_a.is_some());

            engine_a.shutdown().await.unwrap();
            engine_b.shutdown().await.unwrap();
            engine_c.shutdown().await.unwrap();
            let _ = (id_b, id_c);
        };

        timeout(Duration::from_secs(60), body)
            .await
            .expect("three-engine convergence test exceeded 60s");
    }
}
