// SyncEngine — top-level coordinator for P2P sync (design.md §3, ticket T-008).
//
// Owns the LoroDoc, the SyncStore, the Transport, and the Bridge. On
// `start(state)` it:
//   1. loads (or generates + persists) the iroh node secret and the
//      shared sync_doc_secret from the `app_state` KV table
//   2. opens the on-disk SyncStore (snapshot + WAL) and hydrates a
//      LoroDoc from it
//   3. brings up the Transport (iroh endpoint + gossip topic)
//   4. wires up three background tasks behind the same CancellationToken:
//        a. local-update pump — every Loro commit fires the doc's
//           `subscribe_local_update` callback; the bytes are appended to
//           the WAL and broadcast on gossip as `WireMsg::Update`
//        b. inbox handler   — drains `Transport::subscribe()`, importing
//           inbound `Update` / `Snapshot` / `StateResponse` payloads and
//           replying to `StateRequest` with the missing-since-vv bytes
//        c. checkpoint scheduler — fires every `CHECKPOINT_INTERVAL` and
//           also on the local-update pump's notification when WAL entries
//           cross `CHECKPOINT_WAL_THRESHOLD`
//
// The local-update callback is the natural echo-storm guard for the
// broadcast path: Loro fires it only for updates generated by THIS
// doc's commits (not for `import()`), so remote messages can't bounce
// back out as broadcasts. The bridge's apply_remote → SQLite path
// (T-010) needs its own guard via the `Origin` marker.

#![allow(dead_code)]

use crate::error::{AppError, Result};
use crate::p2p::bridge::Bridge;
use crate::p2p::doc::SyncDoc;
use crate::p2p::persistence::{SyncStore, CHECKPOINT_WAL_THRESHOLD};
use crate::p2p::transport::{Transport, TransportEvent, WireMsg};
use crate::state::AppState;
use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
use iroh::{EndpointId, SecretKey};
use loro::{ExportMode, VersionVector};
use rand::RngCore;
use std::sync::Arc;
use std::time::Duration;
use tokio::sync::{broadcast, mpsc, Notify};
use tokio::time::interval;
use tokio_util::sync::CancellationToken;
use tokio_util::task::AbortOnDropHandle;
use tracing::{error, info, warn};
use zeroize::Zeroizing;

/// Periodic checkpoint cadence (design.md §9): the engine rewrites the
/// snapshot at most every `CHECKPOINT_INTERVAL`, and also opportunistically
/// when WAL entries exceed `CHECKPOINT_WAL_THRESHOLD`.
const CHECKPOINT_INTERVAL: Duration = Duration::from_secs(60);

pub struct SyncEngine {
    doc: Arc<SyncDoc>,
    store: Arc<SyncStore>,
    transport: Arc<Transport>,
    bridge: Arc<Bridge>,
    endpoint_id: EndpointId,

    cancel: CancellationToken,
    // Holding the loro Subscription keeps the local-update callback
    // registered; dropping the engine drops the subscription.
    _local_sub: loro::Subscription,
    _local_pump: AbortOnDropHandle<()>,
    _inbox_task: AbortOnDropHandle<()>,
    _checkpoint_task: AbortOnDropHandle<()>,
}

impl SyncEngine {
    /// Production entry point. Loads secrets from `app_state`, opens the
    /// on-disk SyncStore under `app_data_dir()/sync/`, brings up the
    /// transport, and spawns all background tasks.
    pub async fn start(state: Arc<AppState>) -> Result<Arc<Self>> {
        let (node_secret, doc_secret) = load_or_init_secrets(&state.pool).await?;

        let store = Arc::new(SyncStore::open(&state.app)?);
        let doc = Arc::new(SyncDoc::from_doc(store.load()?));
        let transport = Arc::new(Transport::start(node_secret, &doc_secret).await?);
        let bridge = Bridge::new();

        Self::start_with_parts(store, doc, transport, bridge).await
    }

    /// Test hook: caller has already built the parts (typically via the
    /// in-memory iroh test relay). Exposes the same task wiring as
    /// `start` without touching SQLite or `app_data_dir`.
    #[doc(hidden)]
    pub async fn start_with_parts(
        store: Arc<SyncStore>,
        doc: Arc<SyncDoc>,
        transport: Arc<Transport>,
        bridge: Arc<Bridge>,
    ) -> Result<Arc<Self>> {
        let endpoint_id = transport.endpoint_id();
        let cancel = CancellationToken::new();
        let checkpoint_notify = Arc::new(Notify::new());

        // -- local-update pump ---------------------------------------------
        // The Loro callback runs synchronously on the commit thread, so we
        // shovel each update onto an unbounded mpsc and let an async task
        // do the WAL write + broadcast. Unbounded is fine: commits are
        // user-paced (~1 per setter call), the consumer drains immediately,
        // and unbounded avoids any chance of blocking the commit hot path.
        let (local_tx, mut local_rx) = mpsc::unbounded_channel::<Vec<u8>>();
        let local_sub = doc.doc().subscribe_local_update(Box::new(move |bytes| {
            // send returns Err only if the receiver task has dropped,
            // which means the engine is shutting down — nothing to do.
            let _ = local_tx.send(bytes.clone());
            true
        }));

        let local_pump = AbortOnDropHandle::new(tokio::spawn({
            let store = store.clone();
            let transport = transport.clone();
            let cancel = cancel.clone();
            let notify = checkpoint_notify.clone();
            async move {
                loop {
                    let bytes = tokio::select! {
                        biased;
                        _ = cancel.cancelled() => break,
                        maybe = local_rx.recv() => match maybe {
                            Some(b) => b,
                            None => break,
                        },
                    };

                    if let Err(e) = store.append_update(&bytes) {
                        error!("wal append failed: {e}");
                    }
                    if store.pending_wal_entries() >= CHECKPOINT_WAL_THRESHOLD {
                        notify.notify_one();
                    }
                    if let Err(e) = transport
                        .broadcast(WireMsg::Update { bytes })
                        .await
                    {
                        // Broadcast failure is non-fatal — peers will resync
                        // via state-request when they reconnect.
                        warn!("local update broadcast failed: {e}");
                    }
                }
            }
        }));

        // -- inbox handler -------------------------------------------------
        let inbox_task = AbortOnDropHandle::new(tokio::spawn({
            let mut rx = transport.subscribe();
            let doc = doc.clone();
            let transport = transport.clone();
            let cancel = cancel.clone();
            async move {
                loop {
                    tokio::select! {
                        biased;
                        _ = cancel.cancelled() => break,
                        ev = rx.recv() => match ev {
                            Ok(TransportEvent::Message { from, payload }) => {
                                handle_inbound(&doc, &transport, &from, payload).await;
                            }
                            Ok(TransportEvent::PeerConnected(id)) => {
                                info!("peer connected: {id}");
                            }
                            Ok(TransportEvent::PeerDisconnected(id)) => {
                                info!("peer disconnected: {id}");
                            }
                            Err(broadcast::error::RecvError::Lagged(n)) => {
                                warn!("inbox lagged {n} messages — state-sync will recover");
                            }
                            Err(broadcast::error::RecvError::Closed) => break,
                        }
                    }
                }
            }
        }));

        // -- checkpoint scheduler ------------------------------------------
        let checkpoint_task = AbortOnDropHandle::new(tokio::spawn({
            let store = store.clone();
            let doc = doc.clone();
            let cancel = cancel.clone();
            let notify = checkpoint_notify.clone();
            async move {
                let mut tick = interval(CHECKPOINT_INTERVAL);
                // Consume the immediate first tick so we don't checkpoint
                // an empty WAL the moment we boot.
                tick.tick().await;
                loop {
                    tokio::select! {
                        biased;
                        _ = cancel.cancelled() => break,
                        _ = tick.tick() => {}
                        _ = notify.notified() => {}
                    }
                    if store.pending_wal_entries() == 0 {
                        continue;
                    }
                    if let Err(e) = store.checkpoint(&doc.doc()) {
                        error!("checkpoint failed: {e}");
                    }
                }
            }
        }));

        info!("sync engine started: endpoint_id={endpoint_id}");

        Ok(Arc::new(Self {
            doc,
            store,
            transport,
            bridge,
            endpoint_id,
            cancel,
            _local_sub: local_sub,
            _local_pump: local_pump,
            _inbox_task: inbox_task,
            _checkpoint_task: checkpoint_task,
        }))
    }

    pub fn endpoint_id(&self) -> EndpointId {
        self.endpoint_id
    }

    pub fn doc(&self) -> Arc<SyncDoc> {
        self.doc.clone()
    }

    pub fn store(&self) -> Arc<SyncStore> {
        self.store.clone()
    }

    pub fn transport(&self) -> Arc<Transport> {
        self.transport.clone()
    }

    pub fn bridge(&self) -> Arc<Bridge> {
        self.bridge.clone()
    }

    /// Force a checkpoint immediately. Called on graceful shutdown.
    pub fn checkpoint_now(&self) -> Result<()> {
        self.store.checkpoint(&self.doc.doc())
    }

    /// Cancel all background tasks and force a final checkpoint. Returns
    /// the held Transport so the caller can `transport.shutdown().await`
    /// — Transport::shutdown takes `self`, which doesn't compose with
    /// the Arc<Transport> lifetime here.
    pub async fn shutdown(&self) -> Result<()> {
        self.cancel.cancel();
        if let Err(e) = self.checkpoint_now() {
            warn!("final checkpoint failed: {e}");
        }
        Ok(())
    }
}

async fn handle_inbound(
    doc: &SyncDoc,
    transport: &Transport,
    from: &str,
    msg: WireMsg,
) {
    match msg {
        WireMsg::Update { bytes } | WireMsg::Snapshot { bytes } => {
            if let Err(e) = doc.doc().import(&bytes) {
                warn!("inbound import from {from} failed: {e}");
            }
        }
        WireMsg::StateRequest { vv: their_vv_bytes } => {
            let their_vv = match VersionVector::decode(&their_vv_bytes) {
                Ok(v) => v,
                Err(e) => {
                    warn!("malformed state vector from {from}: {e}");
                    return;
                }
            };
            let our_vv_bytes = doc.doc().oplog_vv().encode();
            let bytes = match doc.doc().export(ExportMode::updates(&their_vv)) {
                Ok(b) => b,
                Err(e) => {
                    warn!("export updates_since failed: {e}");
                    return;
                }
            };
            let response = WireMsg::StateResponse { vv: our_vv_bytes, bytes };
            if let Err(e) = transport.broadcast(response).await {
                warn!("state response broadcast to {from} failed: {e}");
            }
        }
        WireMsg::StateResponse { bytes, .. } => {
            if let Err(e) = doc.doc().import(&bytes) {
                warn!("state response import from {from} failed: {e}");
            }
        }
    }
}

/// Read the iroh node secret + shared sync_doc_secret from `app_state`,
/// generating + persisting either if missing.
///
/// On-disk format:
///   - `iroh_node_secret`: base64 of the 32-byte ed25519 secret bytes
///   - `sync_doc_secret`:  hex of the 32 raw bytes (matches the QR
///                          payload format from T-012 / design.md §6)
///
/// T-021 will move these into the OS keychain. Until then they live
/// in the SQLite app_state table next to the rest of the per-device
/// flags. The `sync_doc_secret` is wrapped in `Zeroizing` once decoded
/// so it gets scrubbed from RAM on drop.
async fn load_or_init_secrets(
    pool: &sqlx::SqlitePool,
) -> Result<(SecretKey, Zeroizing<Vec<u8>>)> {
    let node_secret = match get_app_state(pool, "iroh_node_secret").await? {
        Some(s) => {
            let raw = B64
                .decode(s.as_bytes())
                .map_err(|e| AppError::Other(format!("decode iroh_node_secret: {e}")))?;
            let arr: [u8; 32] = raw
                .as_slice()
                .try_into()
                .map_err(|_| AppError::Other("iroh_node_secret length != 32".into()))?;
            SecretKey::from_bytes(&arr)
        }
        None => {
            let key = SecretKey::generate();
            let encoded = B64.encode(key.to_bytes());
            set_app_state(pool, "iroh_node_secret", &encoded).await?;
            key
        }
    };

    let doc_secret = match get_app_state(pool, "sync_doc_secret").await? {
        Some(s) => {
            let raw = hex::decode(&s)
                .map_err(|e| AppError::Other(format!("decode sync_doc_secret: {e}")))?;
            if raw.len() != 32 {
                return Err(AppError::Other("sync_doc_secret length != 32".into()));
            }
            Zeroizing::new(raw)
        }
        None => {
            let mut buf = vec![0u8; 32];
            rand::thread_rng().fill_bytes(&mut buf);
            let encoded = hex::encode(&buf);
            set_app_state(pool, "sync_doc_secret", &encoded).await?;
            Zeroizing::new(buf)
        }
    };

    Ok((node_secret, doc_secret))
}

async fn get_app_state(pool: &sqlx::SqlitePool, key: &str) -> Result<Option<String>> {
    let row: Option<(Option<String>,)> =
        sqlx::query_as("SELECT value FROM app_state WHERE key = ?")
            .bind(key)
            .fetch_optional(pool)
            .await?;
    Ok(row.and_then(|(v,)| v))
}

async fn set_app_state(pool: &sqlx::SqlitePool, key: &str, value: &str) -> Result<()> {
    sqlx::query(
        "INSERT INTO app_state (key, value, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP) \
         ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP",
    )
    .bind(key)
    .bind(value)
    .execute(pool)
    .await?;
    Ok(())
}

// ---- Tests ----------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use iroh::{
        address_lookup::memory::MemoryLookup,
        endpoint::presets::Minimal,
        tls::CaRootsConfig,
        Endpoint, EndpointAddr, RelayMap, RelayMode,
    };
    use iroh_gossip::net::GOSSIP_ALPN;
    use std::time::Duration;
    use tempfile::TempDir;
    use tokio::time::timeout;

    /// Build an iroh endpoint configured for the in-memory test relay.
    /// Mirrors the helper in `transport.rs` so engine tests stay
    /// self-contained.
    async fn build_test_endpoint(relay_map: RelayMap) -> Endpoint {
        Endpoint::builder(Minimal)
            .secret_key(SecretKey::generate())
            .alpns(vec![GOSSIP_ALPN.to_vec()])
            .relay_mode(RelayMode::Custom(relay_map))
            .ca_roots_config(CaRootsConfig::insecure_skip_verify())
            .bind()
            .await
            .unwrap()
    }

    fn store_in(tmp: &TempDir, name: &str) -> Arc<SyncStore> {
        Arc::new(SyncStore::open_at(tmp.path().join(name)).unwrap())
    }

    /// T-008 acceptance: start engine, mutate doc, shut down, restart,
    /// mutations are still present AND were broadcast to a peer engine
    /// during the first run.
    #[tokio::test]
    async fn engine_persists_and_broadcasts_mutations() {
        let (relay_map, relay_url, _relay_guard) =
            iroh::test_utils::run_relay_server().await.unwrap();
        let memory_lookup = MemoryLookup::new();

        let tmp = TempDir::new().unwrap();
        let store_a = store_in(&tmp, "a");
        let store_b = store_in(&tmp, "b");

        let body = async {
            // -- bring up two endpoints + cross-register addresses --------
            let ep_a = build_test_endpoint(relay_map.clone()).await;
            let ep_b = build_test_endpoint(relay_map.clone()).await;
            ep_a.address_lookup().unwrap().add(memory_lookup.clone());
            ep_b.address_lookup().unwrap().add(memory_lookup.clone());
            ep_a.online().await;
            ep_b.online().await;
            let id_a = ep_a.id();
            let id_b = ep_b.id();
            memory_lookup
                .add_endpoint_info(EndpointAddr::new(id_a).with_relay_url(relay_url.clone()));
            memory_lookup
                .add_endpoint_info(EndpointAddr::new(id_b).with_relay_url(relay_url.clone()));

            // -- bring up two transports on the same shared secret -------
            let secret = b"engine-test-shared-secret-aabb";
            let transport_a =
                Arc::new(Transport::start_with_endpoint(ep_a, secret, vec![]).await.unwrap());
            let transport_b =
                Arc::new(Transport::start_with_endpoint(ep_b, secret, vec![id_a]).await.unwrap());

            // -- bring up engine A (the one we'll mutate, then restart) --
            let doc_a = Arc::new(SyncDoc::from_doc(store_a.load().unwrap()));
            let engine_a = SyncEngine::start_with_parts(
                store_a.clone(),
                doc_a.clone(),
                transport_a.clone(),
                Bridge::new(),
            )
            .await
            .unwrap();

            // -- bring up engine B (the receiver) ------------------------
            let doc_b = Arc::new(SyncDoc::from_doc(store_b.load().unwrap()));
            let engine_b = SyncEngine::start_with_parts(
                store_b.clone(),
                doc_b.clone(),
                transport_b.clone(),
                Bridge::new(),
            )
            .await
            .unwrap();

            // Wait for the gossip mesh to form before mutating; otherwise
            // the broadcast can race ahead of the join and B never sees it.
            let mut rx_a = transport_a.subscribe();
            let mut rx_b = transport_b.subscribe();
            let join = async {
                let mut a_joined = false;
                let mut b_joined = false;
                while !(a_joined && b_joined) {
                    tokio::select! {
                        ev = rx_a.recv(), if !a_joined => {
                            if let Ok(TransportEvent::PeerConnected(_)) = ev { a_joined = true; }
                        }
                        ev = rx_b.recv(), if !b_joined => {
                            if let Ok(TransportEvent::PeerConnected(_)) = ev { b_joined = true; }
                        }
                    }
                }
            };
            timeout(Duration::from_secs(15), join)
                .await
                .expect("peers did not join in time");

            // -- mutate on A and assert it propagates to B ---------------
            doc_a.set_pref_display_name("Alice").unwrap();
            doc_a
                .set_course_overlay(
                    "12345",
                    crate::p2p::doc::CourseField::IsPinned(true),
                )
                .unwrap();

            let observed = timeout(Duration::from_secs(5), async {
                loop {
                    if doc_b.get_pref_display_name().as_deref() == Some("Alice")
                        && doc_b
                            .get_course_overlay("12345")
                            .and_then(|c| c.is_pinned)
                            == Some(true)
                    {
                        return ();
                    }
                    tokio::time::sleep(Duration::from_millis(50)).await;
                }
            })
            .await;
            assert!(observed.is_ok(), "engine B did not receive A's mutations within 5s");

            // -- shut down A; force its checkpoint -----------------------
            engine_a.shutdown().await.unwrap();
            engine_b.shutdown().await.unwrap();
            drop(engine_a);
            drop(engine_b);
            // Drop transports too so the next iteration can rebind.
            drop(transport_a);
            drop(transport_b);
            drop(doc_a);
            drop(doc_b);
        };

        timeout(Duration::from_secs(45), body)
            .await
            .expect("engine integration test exceeded 45s");

        // -- restart engine A from the same on-disk store ----------------
        // The transport doesn't matter for this assertion — we're proving
        // the WAL/snapshot survived, which is purely a SyncStore concern.
        let reloaded = SyncDoc::from_doc(store_a.load().unwrap());
        assert_eq!(reloaded.get_pref_display_name().as_deref(), Some("Alice"));
        assert_eq!(
            reloaded.get_course_overlay("12345").and_then(|c| c.is_pinned),
            Some(true),
        );
    }

    /// Force the checkpoint scheduler to fire via the WAL-threshold
    /// notify path: append more than `CHECKPOINT_WAL_THRESHOLD` updates
    /// and confirm the snapshot file shows up + the WAL counter resets.
    /// Skips the transport entirely — pure local-update plumbing test.
    #[tokio::test]
    async fn engine_checkpoints_when_wal_threshold_crossed() {
        let (relay_map, _relay_url, _relay_guard) =
            iroh::test_utils::run_relay_server().await.unwrap();
        let tmp = TempDir::new().unwrap();
        let store = store_in(&tmp, "x");
        let doc = Arc::new(SyncDoc::from_doc(store.load().unwrap()));

        // We still need a real Transport to satisfy start_with_parts;
        // a single self-loop endpoint is enough since we never expect
        // a peer.
        let ep = build_test_endpoint(relay_map.clone()).await;
        let transport = Arc::new(
            Transport::start_with_endpoint(ep, b"isolated-engine-secret", vec![])
                .await
                .unwrap(),
        );

        let engine = SyncEngine::start_with_parts(
            store.clone(),
            doc.clone(),
            transport.clone(),
            Bridge::new(),
        )
        .await
        .unwrap();

        // Drive a few past the threshold so the local-update pump kicks
        // the checkpoint notify.
        for i in 0..(CHECKPOINT_WAL_THRESHOLD + 5) {
            doc.set_assignment_overlay(
                &format!("100:{i}"),
                crate::p2p::doc::AssignmentField::Completed(true),
            )
            .unwrap();
        }

        // Wait for the scheduler to wake on the notify and drain.
        let drained = timeout(Duration::from_secs(5), async {
            loop {
                if store.pending_wal_entries() == 0 {
                    return ();
                }
                tokio::time::sleep(Duration::from_millis(50)).await;
            }
        })
        .await;
        assert!(drained.is_ok(), "checkpoint did not fire after threshold");

        engine.shutdown().await.unwrap();
    }
}
